# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=120)),
                ('Price', models.CharField(max_length=120)),
                ('image_url', models.TextField()),
                ('Desciption', models.TextField()),
            ],
        ),
    ]
