# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_instance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='Desciption',
        ),
        migrations.AddField(
            model_name='car',
            name='Colors',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='car',
            name='Engine',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='car',
            name='Varients',
            field=models.TextField(default=''),
        ),
    ]
